<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="phdl" nsURI="http://phdl.sf.net" nsPrefix="phdl">
  <eClassifiers xsi:type="ecore:EClass" name="PhdlModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designs" upperBound="-1"
        eType="#//Design" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designs" upperBound="-1"
        eType="#//Design" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//DeviceElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attr" eSuperTypes="#//DeviceElement #//NetElement #//InstanceElement #//SubInstanceElement #//Referenceable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" eSuperTypes="#//DeviceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PinType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector" eType="#//Vector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinNames" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Info" eSuperTypes="#//DeviceElement #//DesignElement #//NetElement #//PortElement #//InstanceElement #//SubInstanceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Design">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="design" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subdesign" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//DesignElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="#//DesignElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="net" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vector" eType="#//Vector"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="names" upperBound="-1"
        eType="#//ConnectionName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//DesignElement #//Referenceable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array" eType="#//Array"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" eType="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subInst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subDesign" eType="#//Design"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubInstanceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefAttr" eSuperTypes="#//InstanceElement #//Referenceable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Attr"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PinAssign" eSuperTypes="#//InstanceElement #//Assignable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="combined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubAttr" eSuperTypes="#//SubInstanceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Referenceable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refIndices" eType="#//Indices"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//RefTail"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefTail">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Referenceable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refIndices" eType="#//Indices"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//RefTail"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortAssign" eSuperTypes="#//SubInstanceElement #//Assignable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="combined" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" eType="#//Qualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ConnectionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionAssign" eSuperTypes="#//DesignElement #//Assignable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ConnectionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concatenation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//ConnectionRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replicated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replicate" eType="#//ConnectionRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="open" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ConnectionName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slices" eType="#//Slices"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Indices">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lsb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indices" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slices">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lsb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slices" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lsb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lsb" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Qualifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="indices" eType="#//Indices"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referenceable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slices" eType="#//Slices"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concatenation" eType="#//Concatenation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PinType">
    <eLiterals name="Pin" literal="pin"/>
    <eLiterals name="Input" value="1" literal="inpin"/>
    <eLiterals name="Output" value="2" literal="outpin"/>
    <eLiterals name="InOut" value="3" literal="iopin"/>
    <eLiterals name="Power" value="4" literal="pwrpin"/>
    <eLiterals name="Supply" value="5" literal="suppin"/>
    <eLiterals name="OpenCollector" value="6" literal="ocpin"/>
    <eLiterals name="OpenEmitter" value="7" literal="oepin"/>
    <eLiterals name="Tristate" value="8" literal="tripin"/>
    <eLiterals name="Passive" value="9" literal="passpin"/>
    <eLiterals name="NoConnect" value="10" literal="ncpin"/>
  </eClassifiers>
</ecore:EPackage>
