/*
* generated by Xtext
*/
package edu.byu.ee.phdl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PhdlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return edu.byu.ee.phdl.ui.internal.PhdlActivator.getInstance().getInjector("edu.byu.ee.phdl.Phdl");
	}
	
}
