/*
* generated by Xtext
*/
package edu.byu.ee.phdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.byu.ee.phdl.services.PhdlGrammarAccess;

public class PhdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PhdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_WS");
	}
	
	@Override
	protected edu.byu.ee.phdl.parser.antlr.internal.InternalPhdlParser createParser(XtextTokenStream stream) {
		return new edu.byu.ee.phdl.parser.antlr.internal.InternalPhdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PhdlModel";
	}
	
	public PhdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PhdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
